# Generated by Django 5.0.4 on 2024-04-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=100, verbose_name='نام غذا')),
                ('description', models.CharField(max_length=250, verbose_name='توضیحات')),
                ('price', models.IntegerField(null=True, verbose_name='قیمت غذا')),
                ('foodType', models.IntegerField(choices=[('1', 'صبحانه'), ('2', 'نهار')], default=0, verbose_name='نوع غذا')),
                ('foodImage', models.ImageField(upload_to='', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذاها',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام منو')),
                ('createDate', models.DateField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('expire', models.DateField(verbose_name='زمان انقضاء')),
            ],
            options={
                'verbose_name': 'منو',
                'verbose_name_plural': 'منو ها',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileimage', models.ImageField(upload_to='', verbose_name='تصویر')),
            ],
        ),
    ]
