# Generated by Django 5.0.4 on 2024-04-24 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='status',
            field=models.IntegerField(choices=[('0', 'بسته'), ('1', 'باز')], default=0, verbose_name='وضعیت منو'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.food', verbose_name='')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.menu', verbose_name='منو')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
