# Generated by Django 5.0.4 on 2024-04-24 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_menu_status_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='userName',
        ),
        migrations.AddField(
            model_name='reservation',
            name='userName',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
