# Generated by Django 5.0.4 on 2024-04-26 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_reservation_username_reservation_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.food', verbose_name='غذا'),
        ),
    ]
